export const CEL1922 = {};

CEL1922.MAGICS = {
  internalcinnabar: {
    background: "linear-grey",
    label: "CEL1922.InternalCinnabar",
    aspectlabel: "CEL1922.Metal",
    speciality: {
      essence: {
        label: "CEL1922.Essence",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Metal",
      },
      mind: {
        label: "CEL1922.Mind",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Water",
      },
      purification: {
        label: "CEL1922.Purification",
        classicon: "icon-yinyang",
        icon: "/systems/celestopol1922/images/yin_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CEL1922.Earth",
      },
      manipulation: {
        label: "CEL1922.Manipulation",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Fire",
      },
      aura: {
        label: "CEL1922.Aura",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Wood",
      },
    },
  },
  alchemy: {
    background: "linear-blue",
    label: "CEL1922.Alchemy",
    aspectlabel: "CEL1922.Water",
    speciality: {
      acupuncture: {
        label: "CEL1922.Acupuncture",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Metal",
      },
      elixirs: {
        label: "CEL1922.Elixirs",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Water",
      },
      poisons: {
        label: "CEL1922.Poisons",
        classicon: "icon-yinyang",
        icon: "/systems/celestopol1922/images/yin_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CEL1922.Earth",
      },
      arsenal: {
        label: "CEL1922.Arsenal",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Fire",
      },
      potions: {
        label: "CEL1922.Potions",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Wood",
      },
    },
  },
  masteryoftheway: {
    background: "linear-brown",
    label: "CEL1922.MasteryOfTheWay",
    aspectlabel: "CEL1922.Earth",
    speciality: {
      curse: {
        label: "CEL1922.Curse",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Metal",
      },
      transfiguration: {
        label: "CEL1922.Transfiguration",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Water",
      },
      necromancy: {
        label: "CEL1922.Necromancy",
        classicon: "icon-yinyang",
        icon: "/systems/celestopol1922/images/yin_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CEL1922.Earth",
      },
      climatecontrol: {
        label: "CEL1922.ClimateControl",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Fire",
      },
      goldenmagic: {
        label: "CEL1922.GoldenMagic",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Wood",
      },
    },
  },
  exorcism: {
    background: "linear-red",
    label: "CEL1922.Exorcism",
    aspectlabel: "CEL1922.Fire",
    speciality: {
      invocation: {
        label: "CEL1922.Invocation",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Metal",
      },
      tracking: {
        label: "CEL1922.Tracking",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Water",
      },
      protection: {
        label: "CEL1922.Protection",
        classicon: "icon-yinyang",
        icon: "/systems/celestopol1922/images/yin_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CEL1922.Earth",
      },
      punishment: {
        label: "CEL1922.Punishment",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Fire",
      },
      domination: {
        label: "CEL1922.Domination",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Wood",
      },
    },
  },
  geomancy: {
    background: "linear-green",
    label: "CEL1922.Geomancy",
    aspectlabel: "CEL1922.Wood",
    speciality: {
      neutralization: {
        label: "CEL1922.Neutralization",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_metal.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Metal",
      },
      divination: {
        label: "CEL1922.Divination",
        classicon: "icon-yin",
        icon: "/systems/celestopol1922/images/cde_yin.png",
        elementicon: "/systems/celestopol1922/images/cde_eau.png",
        labelicon: "Yin",
        labelelement: "CEL1922.Water",
      },
      earthlyprayer: {
        label: "CEL1922.EarthlyPrayer",
        classicon: "icon-yinyang",
        icon: "/systems/celestopol1922/images/yin_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_terre.png",
        labelicon: "Yin/Yang",
        labelelement: "CEL1922.Earth",
      },
      heavenlyprayer: {
        label: "CEL1922.HeavenlyPrayer",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_feu.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Fire",
      },
      fungseoi: {
        label: "CEL1922.Fungseoi",
        classicon: "icon-yang",
        icon: "/systems/celestopol1922/images/cde_yang.png",
        elementicon: "/systems/celestopol1922/images/cde_bois.png",
        labelicon: "Yang",
        labelelement: "CEL1922.Wood",
      },
    },
  },
};

CEL1922.SUBTYPES = {
  weapon: {
    id: "weapon",
    label: "CEL1922.Weapon",
  },
  armor: {
    id: "armor",
    label: "CEL1922.Armor",
  },
  vehicle: {
    id: "vehicle",
    label: "CEL1922.Vehicle",
  },
  other: {
    id: "other",
    label: "CEL1922.Other",
  },
};